# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

#########################################################################################
#     Appearance
#########################################################################################

# Set custom theme
  # change 'theme: minimal' to user defined
  # theme available in '/master/data/themes'
theme: chris_theme # my custom theme
day_night: false
font: chris_font # my custom font style
font_size: M # # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

#########################################################################################
# Contact (edit or remove options as required)
#########################################################################################

email: 'chris.moreh@newcastle.ac.uk'
phone: ''
address:
  street: |-
      School of Geography, Politics and Sociology <br>
      Newcastle University <br>
      Room 4.106, Henry Daysh Building <br>
      Newcastle upon Tyne
  city: NE1 7RX
  postcode: United Kingdom
#  country: 'United Kingdom'
#  country_code: UK
coordinates:
  latitude: '54.980548416857076' 
  longitude: '-1.6144048086701253'
#directions: ''
#office_hours:
#  - ''
#contact_links:
#  - icon: twitter
#    icon_pack: fab
#    name: Follow me on Twitter
#    link: 'https://twitter.com/Twitter'
#  - icon: google-scholar
#    icon_pack: ai
#    name: Follow me on Google Scholar
#    link: https://scholar.google.com/citations?user=RqleBzoAAAAJ&hl=en
#  - icon: researchgate
#    icon_pack: ai
#    name: Follow me on ResearchGate
#    link: https://www.researchgate.net/profile/Chris-Moreh
#  - icon: linkedin
#    icon_pack: fab
#    name: Connect with me on LinkedIn
 #   link: https://www.linkedin.com/in/cgm-phd/

#########################################################################################
# Site header
#########################################################################################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: false
  highlight_active_link: true

# Localization

date_format: 'Monday, 02 Jan 2006'
time_format: '15:04'
address_format: en-gb

#########################################################################################
# Site features
#########################################################################################

# Enable source code highlighting? true/false
highlight: true
highlight_languages:
  - r
  - python
  - latex

# Enable LaTeX math rendering? true/false (if false, can be enabled on a per page basis as needed)
math: true

# Enable diagram rendering? true/false (if false, can be enabled on a per page basis as needed)
diagram: true

#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack: false

# Enable visitors to edit pages?
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false

show_related:
  book: false
  page: false
  post: false
  project: false
  publication: false
  event: false

# Display next/previous section pager? (true/false)
section_pager: true
docs_section_pager: true

#########################################################################################
# Other advanced settings
#########################################################################################

# Enable in-built social sharing buttons? (true/false)
# Alternatively, it can be enabled or disabled on a per page basis using share in your page front matter.
# To customize the social networks in the Page Sharer, edit data/page_sharer.toml.
sharing: false

# Show estimated reading time for posts? (true/false)
reading_time: true

copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'

abstract_length: 135

plugins_js: []

avatar:
  gravatar: false
  shape: circle

# Configuration of publication pages.
publications:
  date_format: January 2006
  citation_style: apa
  # Link the title of the publication to the publication
  links_title: false
  # Link the authors of the publication to the list of publication made by this author
  links_authors: false  

# Configuration of projects pages.
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2

breadcrumb:
  page_types:
    book: true

comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''

search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

map:
  provider: mapnik
  api_key: ''
  zoom: 15

marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''

cms:
  branch: master
  local_backend: false

icon:
  pack:
    ai: true